-- Personal Memory Agent · self-hosted PostgreSQL baseline
-- The database is private infrastructure. Only the Hono API should connect to it.
-- IMPORTANT: execute this file as the same PostgreSQL role used by DATABASE_URL.
-- Running it as another owner (for example postgres) can leave the app role unable
-- to perform future schema upgrades. Use database/repair_ownership.sql to repair
-- an existing installation with mismatched ownership.

begin;

create extension if not exists pgcrypto;
create extension if not exists citext;

create table if not exists users (
  id uuid primary key default gen_random_uuid(),
  email citext not null unique,
  password_hash text not null,
  role text not null default 'user' check (role in ('user','admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists users_role_idx on users(role);

create table if not exists system_settings (
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists sessions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references users(id) on delete cascade,
  token_hash text not null unique,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);
create index if not exists sessions_user_idx on sessions(user_id);
create index if not exists sessions_expiry_idx on sessions(expires_at);

create table if not exists auth_codes (
  id text primary key,
  email citext not null,
  purpose text not null check (purpose in ('login','signup','reset')),
  code_hash text not null,
  expires_at timestamptz not null,
  attempts integer not null default 0 check (attempts >= 0),
  consumed_at timestamptz,
  request_ip text,
  created_at timestamptz not null default now()
);
create index if not exists auth_codes_email_created_idx on auth_codes(email, created_at desc);
create index if not exists auth_codes_expiry_idx on auth_codes(expires_at);

create table if not exists entries (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references users(id) on delete cascade,
  raw_text text not null,
  title text,
  kind text check (kind is null or kind in ('idea','material','todo','note')),
  summary text,
  key_points text[] not null default '{}',
  action_items text[] not null default '{}',
  tags text[] not null default '{}',
  status text not null default 'inbox' check (status in ('inbox','active','done','archived')),
  priority text not null default 'normal' check (priority in ('high','normal','low')),
  due_date date,
  ai_state text not null default 'pending' check (ai_state in ('pending','done','failed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists entries_owner_created_idx on entries(owner_id, created_at desc);
create index if not exists entries_owner_kind_idx on entries(owner_id, kind);
create index if not exists entries_owner_status_idx on entries(owner_id, status);

create table if not exists entry_links (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references users(id) on delete cascade,
  source_id bigint not null references entries(id) on delete cascade,
  target_id bigint not null references entries(id) on delete cascade,
  reason text,
  created_at timestamptz not null default now(),
  constraint entry_links_not_self check (source_id <> target_id),
  constraint entry_links_unique unique (owner_id, source_id, target_id)
);
create index if not exists entry_links_owner_source_idx on entry_links(owner_id, source_id);
create index if not exists entry_links_owner_target_idx on entry_links(owner_id, target_id);

create table if not exists entry_chunks (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references users(id) on delete cascade,
  entry_id bigint not null references entries(id) on delete cascade,
  chunk_index integer not null check (chunk_index >= 0),
  content text not null,
  created_at timestamptz not null default now(),
  constraint entry_chunks_unique unique (owner_id, entry_id, chunk_index)
);
create index if not exists entry_chunks_owner_entry_idx on entry_chunks(owner_id, entry_id);

create table if not exists reviews (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references users(id) on delete cascade,
  period_label text not null,
  range_start date,
  range_end date,
  summary text,
  actions text[] not null default '{}',
  stats jsonb not null default '{}'::jsonb,
  entry_count integer not null default 0,
  created_at timestamptz not null default now()
);
create index if not exists reviews_owner_created_idx on reviews(owner_id, created_at desc);

create table if not exists preferences (
  owner_id uuid primary key references users(id) on delete cascade,
  theme jsonb not null default '{}'::jsonb,
  effect jsonb not null default '{}'::jsonb,
  ai jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists ai_usage (
  user_id uuid not null references users(id) on delete cascade,
  usage_date date not null,
  calls integer not null default 0 check (calls >= 0),
  primary key (user_id, usage_date)
);

commit;
