-- Personal Memory Agent baseline schema
-- PostgreSQL / WorkBuddy Cloud (Supabase-style auth.uid()).
-- New environments can apply this file top-to-bottom. Existing environments should
-- review the statements before applying and keep a backup.

begin;

create table if not exists public.entries (
  id bigint generated by default as identity primary key,
  owner_id uuid not null default auth.uid(),
  raw_text text not null,
  title text,
  kind text check (kind is null or kind in ('idea','material','todo','note')),
  summary text,
  key_points text[] not null default '{}',
  action_items text[] not null default '{}',
  tags text[] not null default '{}',
  status text not null default 'inbox' check (status in ('inbox','active','done','archived')),
  priority text not null default 'normal' check (priority in ('high','normal','low')),
  due_date date,
  ai_state text not null default 'pending' check (ai_state in ('pending','done','failed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists entries_owner_created_idx
  on public.entries (owner_id, created_at desc);
create index if not exists entries_owner_kind_idx
  on public.entries (owner_id, kind);
create index if not exists entries_owner_status_idx
  on public.entries (owner_id, status);

create table if not exists public.entry_links (
  id bigint generated by default as identity primary key,
  owner_id uuid not null default auth.uid(),
  source_id bigint not null references public.entries(id) on delete cascade,
  target_id bigint not null references public.entries(id) on delete cascade,
  reason text,
  created_at timestamptz not null default now(),
  constraint entry_links_not_self check (source_id <> target_id),
  constraint entry_links_unique unique (owner_id, source_id, target_id)
);

create index if not exists entry_links_owner_source_idx
  on public.entry_links (owner_id, source_id);
create index if not exists entry_links_owner_target_idx
  on public.entry_links (owner_id, target_id);

create table if not exists public.entry_chunks (
  id bigint generated by default as identity primary key,
  owner_id uuid not null default auth.uid(),
  entry_id bigint not null references public.entries(id) on delete cascade,
  chunk_index integer not null check (chunk_index >= 0),
  content text not null,
  created_at timestamptz not null default now(),
  constraint entry_chunks_unique unique (owner_id, entry_id, chunk_index)
);

create index if not exists entry_chunks_owner_entry_idx
  on public.entry_chunks (owner_id, entry_id);

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  owner_id uuid not null default auth.uid(),
  period_label text not null,
  range_start date,
  range_end date,
  summary text,
  actions text[] not null default '{}',
  stats jsonb not null default '{}'::jsonb,
  entry_count integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists reviews_owner_created_idx
  on public.reviews (owner_id, created_at desc);

create table if not exists public.preferences (
  owner_id uuid primary key default auth.uid(),
  theme jsonb not null default '{}'::jsonb,
  effect jsonb not null default '{}'::jsonb,
  ai jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.entries enable row level security;
alter table public.entry_links enable row level security;
alter table public.entry_chunks enable row level security;
alter table public.reviews enable row level security;
alter table public.preferences enable row level security;

drop policy if exists entries_owner_all on public.entries;
create policy entries_owner_all on public.entries
  for all using (owner_id = auth.uid())
  with check (owner_id = auth.uid());

drop policy if exists entry_links_owner_all on public.entry_links;
create policy entry_links_owner_all on public.entry_links
  for all using (
    owner_id = auth.uid()
    and exists (select 1 from public.entries e where e.id = source_id and e.owner_id = auth.uid())
    and exists (select 1 from public.entries e where e.id = target_id and e.owner_id = auth.uid())
  )
  with check (
    owner_id = auth.uid()
    and exists (select 1 from public.entries e where e.id = source_id and e.owner_id = auth.uid())
    and exists (select 1 from public.entries e where e.id = target_id and e.owner_id = auth.uid())
  );

drop policy if exists entry_chunks_owner_all on public.entry_chunks;
create policy entry_chunks_owner_all on public.entry_chunks
  for all using (
    owner_id = auth.uid()
    and exists (select 1 from public.entries e where e.id = entry_id and e.owner_id = auth.uid())
  )
  with check (
    owner_id = auth.uid()
    and exists (select 1 from public.entries e where e.id = entry_id and e.owner_id = auth.uid())
  );

drop policy if exists reviews_owner_all on public.reviews;
create policy reviews_owner_all on public.reviews
  for all using (owner_id = auth.uid())
  with check (owner_id = auth.uid());

drop policy if exists preferences_owner_all on public.preferences;
create policy preferences_owner_all on public.preferences
  for all using (owner_id = auth.uid())
  with check (owner_id = auth.uid());

-- Existing keyword API used by the current frontend.
create or replace function public.pma_search_entries(
  keyword text default '',
  kind_filter text default null,
  status_filter text default null
)
returns setof public.entries
language sql
stable
security invoker
set search_path = public
as $$
  select e.*
  from public.entries e
  where e.owner_id = auth.uid()
    and (kind_filter is null or e.kind = kind_filter)
    and (status_filter is null or e.status = status_filter)
    and (
      coalesce(keyword, '') = ''
      or concat_ws(
        ' ',
        coalesce(e.title, ''),
        coalesce(e.raw_text, ''),
        coalesce(e.summary, ''),
        array_to_string(e.tags, ' '),
        array_to_string(e.key_points, ' ')
      ) ilike '%' || keyword || '%'
    )
  order by e.created_at desc
  limit 300;
$$;

-- Retrieval API for Ask. It combines full-query substring hits, token hits,
-- simple PostgreSQL FTS ranking and a small recency tie-breaker.
create or replace function public.pma_retrieve_entries(
  query_text text,
  kind_filter text default null,
  status_filter text default null,
  p_limit integer default 40
)
returns setof public.entries
language sql
stable
security invoker
set search_path = public
as $$
  with base as (
    select
      e.*,
      lower(concat_ws(
        ' ',
        coalesce(e.title, ''),
        coalesce(e.raw_text, ''),
        coalesce(e.summary, ''),
        array_to_string(e.tags, ' '),
        array_to_string(e.key_points, ' '),
        array_to_string(e.action_items, ' ')
      )) as hay
    from public.entries e
    where e.owner_id = auth.uid()
      and (kind_filter is null or e.kind = kind_filter)
      and (status_filter is null or e.status = status_filter)
  ),
  scored as (
    select
      b.*,
      (
        case when b.hay ilike '%' || lower(trim(coalesce(query_text, ''))) || '%' then 8 else 0 end
        + coalesce((
            select sum(case when length(tok) >= 2 and b.hay ilike '%' || tok || '%' then 1.5 else 0 end)
            from regexp_split_to_table(lower(trim(coalesce(query_text, ''))), E'\\s+') tok
          ), 0)
        + ts_rank_cd(
            to_tsvector('simple', b.hay),
            websearch_to_tsquery('simple', coalesce(query_text, ''))
          ) * 6
        + greatest(0, 1 - extract(epoch from (now() - b.created_at)) / 2592000.0) * 0.15
      )::double precision as score
    from base b
  )
  select
    s.id, s.owner_id, s.raw_text, s.title, s.kind, s.summary, s.key_points,
    s.action_items, s.tags, s.status, s.priority, s.due_date, s.ai_state,
    s.created_at, s.updated_at
  from scored s
  where s.score > 0
  order by s.score desc, s.created_at desc
  limit greatest(1, least(coalesce(p_limit, 40), 100));
$$;

-- Atomic link replacement. A failure rolls the whole function call back.
create or replace function public.pma_replace_links(
  p_source_id bigint,
  p_target_ids bigint[],
  p_reason text default null
)
returns setof public.entry_links
language plpgsql
security invoker
set search_path = public
as $$
begin
  if not exists (
    select 1 from public.entries
    where id = p_source_id and owner_id = auth.uid()
  ) then
    raise exception 'source entry not found';
  end if;

  delete from public.entry_links
  where owner_id = auth.uid() and source_id = p_source_id;

  insert into public.entry_links (source_id, target_id, reason)
  select p_source_id, target_id, nullif(p_reason, '')
  from unnest(coalesce(p_target_ids, '{}'::bigint[])) as target_id
  where target_id <> p_source_id
    and exists (
      select 1 from public.entries e
      where e.id = target_id and e.owner_id = auth.uid()
    )
  on conflict (owner_id, source_id, target_id) do update
    set reason = excluded.reason;

  return query
    select * from public.entry_links
    where owner_id = auth.uid() and source_id = p_source_id
    order by id;
end;
$$;

-- Atomic entry delete; FKs cascade links/chunks in the same transaction.
create or replace function public.pma_delete_entry(p_entry_id bigint)
returns boolean
language plpgsql
security invoker
set search_path = public
as $$
declare
  deleted_count integer;
begin
  delete from public.entries
  where id = p_entry_id and owner_id = auth.uid();

  get diagnostics deleted_count = row_count;
  return deleted_count > 0;
end;
$$;

-- Keeps chunk rows in sync for long notes/documents. This is the storage
-- foundation for later semantic embeddings without changing the entry model.
create or replace function public.pma_replace_entry_chunks(
  p_entry_id bigint,
  p_chunks text[]
)
returns void
language plpgsql
security invoker
set search_path = public
as $$
begin
  if not exists (
    select 1 from public.entries
    where id = p_entry_id and owner_id = auth.uid()
  ) then
    raise exception 'entry not found';
  end if;

  delete from public.entry_chunks
  where owner_id = auth.uid() and entry_id = p_entry_id;

  insert into public.entry_chunks (entry_id, chunk_index, content)
  select p_entry_id, ordinality - 1, chunk
  from unnest(coalesce(p_chunks, '{}'::text[])) with ordinality as x(chunk, ordinality)
  where length(trim(chunk)) > 0;
end;
$$;

commit;
